### ISSUE TITLE
more then 1 token

### ISSUE THREAD

**Issue by RandomVersion** [Smug246/Discord-Mass-Reporter#1]

**Comment by Smug246** [comment]
sorry what?

**Comment by BlobDevv** [comment]
skidded + not working btw

**Comment by Smug246** [comment]
mf im not a skid and if so skidded from who? and all mass reporters have been patched

**Comment by RandomVersion** [comment]
add an option to mass report with multiple tokens + proxies and multi threading

**Comment by Smug246** [comment]
i will when i find a way to get around the patch

**Comment by RandomVersion** [comment]
closing this for now since no bypass
